# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md013.md
MD013:
  line_length: 80
  heading_line_length: 80
  code_block_line_length: 80
  code_blocks: false
  tables: true
  headings: true
  strict: false
  stern: true
