"$schema" = 'https://starship.rs/config-schema.json'

format = """
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[ ](fg:#769ff0)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 0
truncate_to_repo = false
