# Created by ./starship_themes_generate.sh

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[  ](bg:#a3d2a5 fg:#090c0c)\
[](bg:#76f08a fg:#a3d2a5)\
$directory\
[ ](fg:#76f08a)\
\n$character"""

[directory]
style = "fg:#090c0c bg:#76f08a"
format = "[ $path ]($style)"
truncation_length = 0
truncate_to_repo = false
