name: markdown

on:
  workflow_dispatch:
    inputs:
      markdownlint-cli2-version:
      node-version:
      pandoc-version:
  pull_request:
    paths:
      - '**/*.md'
      - '.github/workflows/markdown.yml'
      - '.markdownlint.yml'

env:
  ZQ88C5ADW6_MARKDOWNLINT_CLI2_VERSION: ${{ inputs.markdownlint-cli2-version || '0.17.2' }}
  ZQ88C5ADW6_NODE_VERSION: ${{ inputs.node-version || '22' }}
  ZQ88C5ADW6_PANDOC_VERSION: ${{ inputs.pandoc-version || '3.6.4' }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: install node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.ZQ88C5ADW6_NODE_VERSION }}

      - name: install markdownlint-cli2
        run: |
          set -euo pipefail
          args=(
            npm
            install
            --fund=false
            --audit=false
            --global
            'markdownlint-cli2@${{ env.ZQ88C5ADW6_MARKDOWNLINT_CLI2_VERSION }}'
          )
          echo "${args[*]}"
          exec "${args[@]}"

      - name: run markdownlint-cli2
        run: markdownlint-cli2 '**/*.md'

  pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: install pandoc
        run: |
          set -xveuo pipefail
          readonly pandoc_url='https://github.com/jgm/pandoc/releases/download/${{ env.ZQ88C5ADW6_PANDOC_VERSION }}/pandoc-${{ env.ZQ88C5ADW6_PANDOC_VERSION }}-linux-amd64.tar.gz'
          readonly pandoc_tarball='${{ runner.temp }}/pandoc.tar.gz'
          wget "$pandoc_url" -O "$pandoc_tarball"
          tar --strip-components=1 -xf "$pandoc_tarball" -C '${{ runner.temp }}'
          echo 'pandoc_exe=${{ runner.temp }}/bin/pandoc' >>"$GITHUB_ENV"

      - name: run pandoc
        run: |
          set -xveuo pipefail
          "$pandoc_exe" -s --toc -o LinuxSetup.html -f commonmark_x -t html LinuxSetup.md --fail-if-warnings=true

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'pandoc-outputs'
          path: 'LinuxSetup.html'
